- hosts: 'cluster_nodes'
  become: yes

  tasks:
    - name: create the kube user account
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: sudo=present
      ansible.builtin.package:
        name: sudo
        state: present

    - name: allow 'kube' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key: user=kube key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: set up authorized keys for the root user
      authorized_key: user=root key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
